import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#eeb12e',
        'on-error': '#ffffff',
        'tertiary-dim': '#745200',
        'primary-dim': '#a5292f',
        'secondary-container': '#88e9f8',
        'error-dim': '#9f0519',
        'on-surface': '#383835',
        'on-tertiary-fixed-variant': '#634600',
        'on-background': '#383835',
        'surface-container-highest': '#eae8e2',
        'tertiary-container': '#febf3c',
        'surface-container-low': '#fcf9f4',
        'on-tertiary': '#ffffff',
        'surface-container': '#f6f3ee',
        'primary': '#b6353a',
        'surface-variant': '#eae8e2',
        'secondary-dim': '#00626c',
        'outline': '#82807c',
        'on-error-container': '#570008',
        'tertiary': '#835e00',
        'on-primary': '#ffffff',
        'surface': '#fffcf7',
        'on-secondary-container': '#00555e',
        'primary-container': '#ff7574',
        'on-tertiary-fixed': '#3f2b00',
        'on-secondary-fixed': '#004148',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#656461',
        'on-primary-fixed': '#000000',
        'surface-bright': '#fffcf7',
        'on-primary-container': '#4e0009',
        'inverse-on-surface': '#9e9d98',
        'primary-fixed-dim': '#f56364',
        'outline-variant': '#bbb9b4',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#88e9f8',
        'inverse-primary': '#ff6b6b',
        'surface-tint': '#b6353a',
        'on-tertiary-container': '#583d00',
        'secondary-fixed-dim': '#79dae9',
        'secondary': '#006f7b',
        'tertiary-fixed': '#febf3c',
        'background': '#fffcf7',
        'surface-dim': '#e5e2dc',
        'inverse-surface': '#0e0e0c',
        'on-primary-fixed-variant': '#60000d',
        'surface-container-high': '#f0eee8',
        'primary-fixed': '#ff7574',
        'error': '#c0262d',
        'error-container': '#fb5151',
        'on-secondary-fixed-variant': '#005f6a',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['var(--font-newsreader)', 'serif'],
        body: ['var(--font-jakarta)', 'sans-serif'],
        label: ['var(--font-jakarta)', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};

export default config;
